### ISSUE TITLE
Lỗi khi loadmore

### ISSUE THREAD

**Issue by manhpham90vn** [tuan188/MGAPIService#1]
chào bạn, khi mình loadmore phần repo list trong lúc mình không có wifi thì thấy log call nhiều api một lúc

**Comment by tuan188** [comment]
Cái này theo mình nghĩ không phải lỗi của APIService mà nguyên nhân nằm ở phần load more ở bên table view, bạn thử kiểm tra xem có phải nó trigger load more quá nhiều không

**Comment by manhpham90vn** [comment]
mình thấy bạn mới up lên bản mới khi chạy pod install thì không được, bạn có thể update file Podfile.lock được không

**Comment by manhpham90vn** [comment]
và bị thêm lỗi
`Compiling for iOS 9.0, but module 'MGArchitecture' has a minimum deployment target of iOS 10.0: /Users/manh/Library/Developer/Xcode/DerivedData/MGAPIService-bbanikopqfbldjbldhfzitlmfxwz/Build/Products/Debug-iphonesimulator/MGArchitecture/MGArchitecture.swiftmodule/x86_64-apple-ios-simulator.swiftmodule`
bạn sửa lại Deploymnet Info Target nhé

**Comment by manhpham90vn** [comment]
còn vấn đề lúc đầu mình nói nếu bạn đặt 
`.debug()` trong RepoRepository.swift thì bạn sẽ thấy có 2 event next được phát ra kể cả trường hợp vẫn có mạng bình thường lên mình nghĩ phần core đang có vấn đề

**Comment by tuan188** [comment]
> còn vấn đề lúc đầu mình nói nếu bạn đặt
> `.debug()` trong RepoRepository.swift thì bạn sẽ thấy có 2 event next được phát ra kể cả trường hợp vẫn có mạng bình thường lên mình nghĩ phần core đang có vấn đề

mình thử kiểm tra lại ở trong 2 TH online/offline thì phần log chỉ có 1 request

**Comment by tuan188** [comment]
> mình thấy bạn mới up lên bản mới khi chạy pod install thì không được, bạn có thể update file Podfile.lock được không

ở commit mới nhất thì podfile.lock đã được update bạn nhé

**Comment by tuan188** [comment]
> và bị thêm lỗi
> `Compiling for iOS 9.0, but module 'MGArchitecture' has a minimum deployment target of iOS 10.0: /Users/manh/Library/Developer/Xcode/DerivedData/MGAPIService-bbanikopqfbldjbldhfzitlmfxwz/Build/Products/Debug-iphonesimulator/MGArchitecture/MGArchitecture.swiftmodule/x86_64-apple-ios-simulator.swiftmodule`
> bạn sửa lại Deploymnet Info Target nhé

bạn dùng bản 1.3.1 nhé
