### ISSUE TITLE
Hỏi về cách xử lý hot và cold trong base

### ISSUE THREAD

**Issue by manhpham90vn** [tuan188/MGAPIService#2]
Chào bạn tại dòng 108 file APIServiceBase
`return self.manager.rx` mình thấy gọi tới hàm upload của RxAlamofire sau đó gọi tới hàm `Observable.create` theo mình biết thì hàm này tạo ra một Cold Observable nó sẽ tự clone ra thành nhiều stream nếu có nhiều subscribe trong khi đó mình thấy code của bạn ko dùng hàm 
`.share()` để convert sang Hot Observable
Bạn có thể giải thích giúp mình chỗ này được không ạ

**Comment by tuan188** [comment]
Mình cũng mới gặp 1 bug liên quan tới vấn đề này trong dự án, đúng là nếu subscribe nhiều lần sẽ request nhiều lần. Nếu viết theo kiểu CleanArchitecture thì TH này cũng hiếm gặp. Bạn có thể chủ động thêm .share() trong Repository layer hoặc override hàm request trong subclass của APIServiceBase.
